### ISSUE TITLE
Expose guppy parameters to the user

### ISSUE THREAD

**Issue by alneberg** [nf-core/nanoseq#10]
We found out that we had to tweak the `--gpu_runners_per_device` parameter to guppy so it would be good to enable user to do this as this parameter is highly specific to what type of GPU you have. Should probably do this for other guppy parameters as well such as `--cpu_threads_per_caller` and `--num_callers`.

**Comment by drpatelh** [comment]
Good idea! Im still not entirely sure how best to use these parameters given a certain compute infrastructure...agree if they are explicitly defined then they can be tweaked.

**Comment by alneberg** [comment]
Same here, we got CUDA memory error with 6 callers, but managed to get around with anything lower than that. Basically trial and error from our side.

**Comment by drpatelh** [comment]
Based on the fact that the pipeline has been tested now by various users I think  the current user-provided parameter set should be sufficient. Feel free to reopen if you can think of more 👍
