### ISSUE TITLE
Error "cat: '*.fastq.gz': No such file or directory" when adding additional Guppy parameters

### ISSUE THREAD

**Issue by pcantalupo** [nf-core/nanoseq#104]
Hello, I tried to run the pipeline (`-r dev`) into accepting additional Guppy parameters so that Guppy would perform Qscore filtering of fastq into "pass" and "fail" groups.  However the pipeline failed with this error `Command error:
  cat: '*.fastq.gz': No such file or directory`

The command line that I used was
`nextflow run nf-core/nanoseq --input samplesheet.csv --protocol cDNA --input_path ./fast5_pass --flowcell 'FLO-MIN106 --qscore_filtering --min_qscore 7' --kit SQK-DCS109 --skip_demultiplexing --skip_quantification -config myconfig.config -profile singularity -r dev`

The contents of my sample sheet and the pipeline_report.txt are listed in this [GIST](https://gist.github.com/pcantalupo/e64e1213d5fe94f41961786a18a48fff). When I look in the nextflow `work` directory used by Guppy, I see that it is properly separating the failed fastq from the passed fastq into their respective `fail` and `pass` directories. But the pipeline doesn't realize that the `*fastq.gz` files are in the `pass` directory and not in the current directory; hence the `cat` error.

**Comment by christopher-hakkaart** [comment]
Guppy removed in #222 - closing issue
