### ISSUE TITLE
guppy_basecaller with gpu: error while loading shared libraries: libcuda.so.1

### ISSUE THREAD

**Issue by asalhab** [nf-core/nanoseq#105]
Hello,
I am trying to run nanoseq on our HPC with singularity. To do so, I created a conda environemnt and installed singularity (3.6.3) and nextflow (20.10.0). I changed  `maksuashfs` path  in the singularity.conf into `mksquashfs path = /home/abdosa/miniconda2/envs/singularity/bin/` (otherwise I get an error not finding `squahfs`).
Finally I submitted this job to our cluster (slurm) -through the submission node- with singularity profile and (runOptions = '--nv') :  `sbatch -J nanoseq_test --wrap="nextflow run nf-core/nanoseq -r 1.1.0 -profile test,singularity -c resources.singularity.nanoseq.slurm.short.config --guppy_gpu --guppy_gpu_runners 6 --gpu_cluster_options '--part=gpu20 --gres=gpu:1'"` . This worked perfectly and the pipeline finished succesfully (without --nv option it failed).

When I ran nanoseq with gpu on my data it failed (with and without --nv option) at the GUPPY (barcode) step becasue of the follwoing error:
```
Error executing process > 'GUPPY (fast5)'

Caused by:
  Process `GUPPY (fast5)` terminated with an error exit status (127)

Command executed:

  guppy_basecaller \
      --input_path fast5 \
      --save_path ./basecalling \
      --records_per_fastq 0 \
      --compress_fastq \
       \
      --device auto --num_callers 12 --cpu_threads_per_caller 2 --gpu_runners_per_device 12 \
       \
      --config dna_r9.4.1_450bps_hac.cfg \

  guppy_basecaller --version &> v_guppy.txt

  ## Concatenate fastq files
  mkdir fastq
  cd basecalling
  if [ "$(find . -type d -name "barcode*" )" != "" ]
  then
      for dir in barcode*/
      do
          dir=${dir%*/}
          cat $dir/*.fastq.gz > ../fastq/$dir.fastq.gz
      done
  else
      cat *.fastq.gz > ../fastq/HM27_0h_R1.fastq.gz
  fi

Command exit status:
  127

Command output:
  (empty)

Command error:
  INFO:    Convert SIF file to sandbox...
  guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
  INFO:    Cleaning up image...

```

I logged-in to the gpu node and checked the follwoing:
```
abdosa@gpu20-20:~$ nvidia-smi
Mon Feb  1 10:32:09 2021
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Quadro RTX 8000     On   | 00000000:44:00.0 Off |                  Off |
| 33%   30C    P8    11W / 260W |      0MiB / 48601MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

abdosa@gpu20-20:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Tue_Jun_12_23:07:04_CDT_2018
Cuda compilation tools, release 9.2, V9.2.148
```

Then I activated singularity conda environemnt and started the  genomicpariscentre-guppy-gpu-4.0.14.img image with interactive shell and ran` guppy_basecaller --help` but I got the same error: 
`guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory
`

```
singularity shell genomicpariscentre-guppy-gpu-4.0.14.img
INFO:    Convert SIF file to sandbox...
Singularity> nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```

when I look at the submission node into /usr/lib/ I can find the follwoing directories: cuda/      cuda-10.0/ cuda-10.1/ cuda-9.0/  cuda-9.2/

could you please help debugging this error
Thank you
Abdul

**Comment by mlorthiois** [comment]
Hello,

I also have the same problem, under the same conditions: using nanoseq with slurm executor trying to run the basecalling process on a node with a gpu.

When I run the process directly from a gpu node with the `local` executor and not `slurm`, the process runs perfectly, but forces me to run all nanoseq steps on a gpu node so not ideal...

Did you finally find a solution?

Thank you
Matthias

**Comment by asalhab** [comment]
Hello Matthias,
it worked for me after changing  "-profile singularity" option in my command to "-with-singularity" option and added "--nv" to singularity.runOptions.
Sorry I didn't write the solution here since the discussion were moved to slack
https://nfcore.slack.com/archives/CP9GUPH35/p1614260137000300?thread_ts=1612886910.090000&cid=CP9GUPH35

**Comment by richardtillett** [comment]
I get the same error, but am running via docker. I wonder what the solution for me is...

**Comment by trum994** [comment]
I have the same problem. Using singularity. 
`  guppy_basecaller: error while loading shared libraries: libcuda.so.1: cannot open shared object file: No such file or directory`
I tried @asalhab's recommendation to no avail. I get something like "nv not avaible on this host" despite being on a gpu node. @asalhab do you mind sharing the relevant parameters? I do not have access to that slack channel. 

Also I believe what that does is to force every single step of the whole workflow to run on a gpu as @mlorthiois  mentioned.

**Comment by trum994** [comment]
So I ended up keeping the `-profile singularity` but added a custom config that looked like this:
```
singularity {
	enabled = true
	runOptions = '--nv -B <your-cuda-driver-path>/libs/current/lib64:/usr/local/nvidia/lib64 -B <your-cuda-river-path>/libs/current/bin:/usr/local/sbin'
}
```
which made guppy step happy. You may not need the `-B` parameter.

**Comment by christopher-hakkaart** [comment]
Guppy removed in #222 - closing issue
