### ISSUE TITLE
Failed to pass path of testdata azure

### ISSUE THREAD

**Issue by vsmalladi** [nf-core/nanoseq#151]
## Check Documentation

I have checked the following places for your error:

- [x] [nf-core website: troubleshooting](https://nf-co.re/usage/troubleshooting)
- [x] [nf-core/nanoseq pipeline documentation](https://nf-co.re/nanoseq/usage)

## Description of the bug

 Missing output file(s) `test-datasets/fast5/barcoded/` expected by process `GET_TEST_DATA`

## Steps to reproduce

Steps to reproduce the behaviour:

1. nextflow run nf-core/nanoseq -profile test,azurebatch -r 1.1.0
2. Missing output file(s) `test-datasets/fast5/barcoded/` expected by process `GET_TEST_DATA`

## Expected behaviour

Should be able to pass the files to the next step

## Log files

Have you provided the following extra information/files:

- [ ] The command used to run the pipeline
- [ ] The `.nextflow.log` file 

## System

- Hardware: Azure
- Executor: Azure Batch

## Nextflow Installation

- Version: 21.10.5.5658

## Container engine

- Engine: Docker

**Comment by yuukiiwa** [comment]
https://github.com/nf-core/nanoseq/pull/152
