### ISSUE TITLE
typo in subway map

### ISSUE THREAD

**Issue by maxulysse** [nf-core/nanoseq#174]
`Nanopore basecalling, demultiplexing, QC, alignment, and downstram analysis`
should be:
`Nanopore basecalling, demultiplexing, QC, alignment, and downstream analysis`

**Comment by christopher-hakkaart** [comment]
Good spot @maxulysse! I've corrected it [here](https://github.com/nf-core/nanoseq/commit/15658ca9411cd89a5ca3d84a47cec9a2300ae523) and will merged into dev with other fixes soon.
