### ISSUE TITLE
Error on running profile test 

### ISSUE THREAD

**Issue by xmeng** [nf-core/nanoseq#190]
### Description of the bug

$nextflow pull nf-core/nanoseq 
Checking nf-core/nanoseq ...
Already-up-to-date - revision: 1e60482a2c [master]
(base) [ec2-user@ip-1-9-8 nf-nanoseq]$ nextflow run nf-core/nanoseq -profile test,docker --outdir test_dir
N E X T F L O W  ~  version 20.01.0
Launching `nf-core/nanoseq` [soggy_snyder] - revision: 1e60482a2c [master]
Unknown config attribute `params.genomes.GRCh37.projectDir` -- check config file: /home/ec2-user/.nextflow/assets/nf-core/nanoseq/nextflow.config

How to ignore the 'params.genomes.GRCh37.projectDir' ?  Thanks.

**Comment by christopher-hakkaart** [comment]
Hi @xmeng, I can't seem to replicate the problem. It runs all the way through for me using the same command: `nextflow run nf-core/nanoseq -profile test,docker --outdir test_dir`

I see your running an older version of Nextflow which might be causing some problems. Try updating it using `nextflow self-update` and see if you get the same problem

**Comment by xmeng** [comment]
Thanks for your reply. It works after I upgraded nextflow.
