### ISSUE TITLE
Error executing process > 'NFCORE_NANOSEQ:NANOSEQ:RNA_FUSIONS_JAFFAL:UNTAR (null)'

### ISSUE THREAD

**Issue by MustafaElshani** [nf-core/nanoseq#192]
I have been getting this error
```

Error executing process > 'NFCORE_NANOSEQ:NANOSEQ:RNA_FUSIONS_JAFFAL:UNTAR (null)'
 Caused by:
Not a valid path value type: org.codehaus.groovy.runtime.NullObject (null)

 Tip: when you have fixed the problem you can continue the execution adding the option `-resume` to the run command line

Failed to invoke `workflow.onComplete` event handler 
 -- Check script '/root/.nextflow/assets/nf-core/nanoseq/./workflows/nanoseq.nf' at line: 524 or see '.nextflow.log' file for more details
```

This is the line I have run it with 

```
nextflow run nf-core/nanoseq \ 

--input nanoseq_samplesheet.csv \ 

--outdir nf-core_NANOSEQ/ \ 

--protocol cDNA \ 

--skip_basecalling \ 

--skip_demultiplexing \ 

-profile docker \ 

--multiqc_title _LongRead_Nanopore_seq \ 

--save_align_intermeds  
```

Any help would be very much be appreciated

**Comment by duocang** [comment]
Hi.

do you fix this problem?

**Comment by amadaes** [comment]
Hi. I have also encountered this issue. Have you found any solutions yet? Thank you.

**Comment by christopher-hakkaart** [comment]
There was an issue with mapping. I've made a branch with the correct mapping and will merge it into dev soon. RNA_FUSIONS_JAFFAL is ram hungry so I'll investigate a way to reduce its requirements before merging.

**Comment by sunsetyerin** [comment]
Hi @christopher-hakkaart when will RNA_FUSIONS_JAFFAL be updated? 
It seems like I cannot move forward from RNA_FUSIONS_JAFFAL error.

**Comment by christopher-hakkaart** [comment]
Have you tried the branch I mentioned above? Or is it to ram hungry for your setup?

**Comment by christopher-hakkaart** [comment]
I haven't tried full sized files but if you have access to some and could check it out for me that would be great

**Comment by christopher-hakkaart** [comment]
The branch is called `fix_jaffal`

**Comment by Jungal10** [comment]
untar the jaffar worked for us

**Comment by christopher-hakkaart** [comment]
Thanks for the update - I've merged this fix into [`update_3_1`](https://github.com/nf-core/nanoseq/tree/update_3_1) and will get the update out soon.
