### ISSUE TITLE
error running the test example run

### ISSUE THREAD

**Issue by sheucke** [nf-core/nanoseq#202]
### Description of the bug

if I try to test the pipeline with:

nextflow run nf-core/nanoseq -r 3.0.0 -profile test,docker --outdir results

I get an error in the log:

Nov-02 07:58:59.240 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'NFCORE_NANOSEQ:NANOSEQ:GET_NANOLYSE_FASTA'

Caused by:
  Process `NFCORE_NANOSEQ:NANOSEQ:GET_NANOLYSE_FASTA` terminated with an error exit status (56)

Command executed:

  curl \
  -L https://github.com/wdecoster/nanolyse/raw/master/reference/lambda.fasta.gz \
  -o lambda.fasta.gz

Command exit status:
  56

Command output:
  (empty)

Command error:
    0     0    0     0    0     0      0      0 --:--:--  0:02:13 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:14 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:15 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:16 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:17 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:18 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:19 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:20 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:21 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:22 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:23 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:24 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:25 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:26 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:27 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:28 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:29 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:30 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:31 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:32 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:33 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:34 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:35 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:36 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:37 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:38 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:39 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:40 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:41 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:42 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:43 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:44 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:45 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:46 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:47 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:48 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:49 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:50 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:51 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:52 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:53 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:54 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:55 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:56 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:57 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:58 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:02:59 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:03:00 --:--:--     0
    0     0    0     0    0     0      0      0 --:--:--  0:03:01 --:--:--     0
  curl: (56) OpenSSL SSL_read: Connection reset by peer, errno 104

Work dir:
  /home/ubuntu/dev/nanoseq/work/bd/457c9c715db4c5a237aeca8311a1df

Any Idea whats wrong? If I run the command in a terminal:

curl \
  -L https://github.com/wdecoster/nanolyse/raw/master/reference/lambda.fasta.gz \
  -o lambda.fasta.gz

It can download the file, but not in the pipeline context.

**Comment by christopher-hakkaart** [comment]
Closing stale issue. Please reopen if you are still having this issue.
