### ISSUE TITLE
Module compilation error

### ISSUE THREAD

**Issue by sunsetyerin** [nf-core/nanoseq#205]
Hi @yuukiiwa, I really want to run this workflow but having some issues here. Can you please take a look? 

### Description of the bug

Module compilation error
- file : /my/path/to/.nextflow/assets/nf-core/nanoseq/modules/nf-core/modules/samtools/faidx/main.nf
- cause: Invalid process definition -- Unknown keyword `stub` @ line 34, column 5.
       """
       ^

1 error

### Command used and terminal output

```console
nextflow run nf-core/nanoseq \
    --input samplesheet.csv \
    --protocol cDNA \
    --skip_basecalling \
    --skip_demultiplexing \
    -profile docker,singularity \
    -bg
```

**Comment by yuukiiwa** [comment]
Hi @sunsetyerin,

For the profile, please use either -profile docker or -profile singularity depending on which container system you have on your machine.

Thanks!

Best wishes,
Yuk Kei
