### ISSUE TITLE
Incorrect usage example at the Documentation section

### ISSUE THREAD

**Issue by Stakaitis** [nf-core/nanoseq#208]
### Description of the bug

[Provided](https://github.com/nf-core/nanoseq#documentation) example on how to launch the pipeline for DNA is incorrect. By running it, an error occurs: 

`--skip_quantification` option needs to be added

### Command used and terminal output

```console
nextflow run nf-core/nanoseq \
    --input samplesheet.csv \
    --protocol DNA \
    --flowcell FLO-MIN106 \
    --kit SQK-LSK109 \
    --barcode_kit SQK-PBK004 \
    -profile singularity

ERROR nextflow.Nextflow - Invalid protocol option if performing quantification: DNA. Valid options: 'cDNA', 'directRNA'
```

**Comment by christopher-hakkaart** [comment]
Nice spot - I've added `--skip_quantification` into the docs and merged it into [update_3_1](https://github.com/nf-core/nanoseq/tree/update_3_1).
