### ISSUE TITLE
Transcriptome aware genome alignment

### ISSUE THREAD

**Issue by lwratten** [nf-core/nanoseq#31]
Looking to implement transcriptome aware genome alignment in `graphmap2` (requires a `gtf` file as input) and `minimap2` (the `--junc_bed` flag does this, requires a `bed12` file as input).

Current idea is to  add an optional column in the samplesheet for a `gtf` or `bed12` file, and then if the selected aligner is `minimap2` and it is in `gtf` format we can convert this to a `bed12`.

Let me know what you think.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nanoseq/pull/46
