### ISSUE TITLE
Basecalling model as input to Guppy

### ISSUE THREAD

**Issue by lwratten** [nf-core/nanoseq#33]
I would like to add a basecalling model option for input to Guppy.
I.e.  take the `.json` output of something like [Taiyaki](https://github.com/nanoporetech/taiyaki) and pass it to Guppy using the `--model` flag. Seems like custom basecalling models are being used more and more so would be super nice to have this in from the first release.

Will need a basecalling model to test it works though which I am finding very difficult to locate.

Thinking something like `--guppy_model` or `--guppy_basecalling_model` as an optional command line parameter to take a `.json` file.

**Comment by drpatelh** [comment]
Docker containers we are currently using in the pipeline:

GPU Docker container:
https://hub.docker.com/r/nanozoo/guppy_gpu/dockerfile

CPU Docker container:
https://hub.docker.com/r/genomicpariscentre/guppy/dockerfile

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nanoseq/pull/44
