### ISSUE TITLE
Improve test-dataset to avoid 255 error

### ISSUE THREAD

**Issue by drpatelh** [nf-core/nanoseq#37]
`-profile test` is currently passing but I have had to bypass a `255` error we are getting when generating the `bigWig` and `bigBed` files because one the samples doesnt  have any reads that map to reference gene sequence. Would be good if we can amend the test-dataset so we dont get this error.

**Comment by lwratten** [comment]
Interestingly this error doesn't occur when using `graphmap2` as the aligner
Tried just obtaining a different subsample from the data, but out of the 10 times I attempted, they could not be demultiplexed successfully 🤦‍♂

**Comment by drpatelh** [comment]
`grapmap2` might be mapping some of the reads whereas `minimap2` doesnt? Could check in the `flagstat` output.

**Comment by drpatelh** [comment]
Since we have changed the test data this doesn't appear to be a problem anymore. Just realised this was still open.
