### ISSUE TITLE
Add -split option for the genomeCoverageBed call

### ISSUE THREAD

**Issue by lwratten** [nf-core/nanoseq#42]
Add `-split` option for `genomeCoverageBed` command in `BAMToBedGraph` process so we don't have reads spanning introns in RNA seq and deletions in DNA.
https://bedtools.readthedocs.io/en/latest/content/tools/genomecov.html

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nanoseq/pull/45
