### ISSUE TITLE
FastQC fails when fastq file is not in gzip format

### ISSUE THREAD

**Issue by lwratten** [nf-core/nanoseq#43]
I found this when I tried to run with the `--skip_basecalling` flag on some data we have
This is due to the symbolic link we create at the start
![image](https://user-images.githubusercontent.com/37123979/70029453-207bd500-15e2-11ea-8cde-d1fd39298179.png)
Are we making it mandatory for the fastq to be gzipped, or will we add a case here so it doesn't break?

**Comment by drpatelh** [comment]
This should fail more elegantly in the `CheckSampleSheet` process right?
https://github.com/nf-core/nanoseq/blob/99a86262ad3fb95dc2d5de50b644fb020dbda1fd/bin/check_samplesheet.py#L80

Shouldnt be able to get to the `FastQC` process unless there is a bug somewhere. What does you sample sheet look like @lwratten ?

Yes, I think we should insist on the `fastq` files being zipped. Much more storage friendly.

**Comment by drpatelh** [comment]
Ok. I found the bug. Basically we arent exiting if the `if` statement above fails. Ill fix in the next PR.

**Comment by drpatelh** [comment]
Fixed in https://github.com/nf-core/nanoseq/pull/46
