### ISSUE TITLE
sample sheet for samples without barcodes

### ISSUE THREAD

**Issue by FranBonath** [nf-core/nanoseq#64]
Currently I have to specify a barcode in the sample sheet even if a sample doesn't have one, only so it can pass the sample sheet check. This happens if we run only a single sample per flowcell. 
Without specifying a barcode kit, demultiplexing will still be skipped in these cases (as should be).

**Comment by cying111** [comment]
Hi @FranBonath, thank you for the feedback! Currently, if you are dealing with samples that do not need demultiplexing, you can just leave the barocode column as empty in the txt file, but you will still need to have this column as it will be checked by the pipeline. I hope this addresses your question.

**Comment by drpatelh** [comment]
Did you manage to get the pipeline running without barcodes @FranBonath ?

**Comment by drpatelh** [comment]
Closing this but feel free to re-open if the issue persists in version 1.1.0.
