### ISSUE TITLE
skipped alignment steps

### ISSUE THREAD

**Issue by mlorthiois** [nf-core/nanoseq#77]
Hi,

When I use Nanoseq with .fasta5 files as input, all the alignement steps are skipped. Here are my commands:
```
nextflow run nf-core/nanoseq \
    -r 1.0.0 \
    -profile singularity \
    --input /home/genouest/cnrs_umr6290/mlorthiois/nanoseq_test/input.csv \
    --protocol cDNA \
    --input_path /home/genouest/cnrs_umr6290/mlorthiois/nanoseq_test/data \
    --flowcell FLO-MIN106 \
    --kit SQK-DCS109 \
    --skip_demultiplexing \
    --max_cpus 30 \
    --igenomes_ignore false 
```

At the end, I get `-[nf-core/nanoseq] Pipeline completed successfully-`, but only these steps are computed:
```
[86/2a19f8] process > CheckSampleSheet (input.csv)   [100%] 1 of 1 ✔
[5b/8e1c88] process > Guppy (data)                   [100%] 1 of 1 ✔
[42/1c9b63] process > PycoQC (sequencing_summary.... [100%] 1 of 1 ✔
[b5/a3702e] process > NanoPlotSummary (sequencing... [100%] 1 of 1 ✔
[-        ] process > NanoPlotFastQ                  -
[-        ] process > FastQC                         -
[-        ] process > GetChromSizes                  -
[-        ] process > GTFToBED                       -
[-        ] process > GraphMap2Index                 -
[-        ] process > GraphMap2Align                 -
[-        ] process > SortBAM                        -
[-        ] process > BAMToBedGraph                  -
[-        ] process > BedGraphToBigWig               -
[-        ] process > BAMToBed12                     -
[-        ] process > Bed12ToBigBed                  -
[23/a0803d] process > output_documentation           [100%] 1 of 1 ✔
[3f/323218] process > get_software_versions          [100%] 1 of 1 ✔
[99/fdd59c] process > MultiQC (1)                    [100%] 1 of 1 ✔
``` 

So I get a `fastq.gz` file by guppy, the only solution I found is to run again Nanoseq, without basecalling and demultiplexing, with the `fastq.gz` as input. In this case, all the steps are computed.

**Comment by drpatelh** [comment]
Hi @mlorthiois ! Apologies for the late response to finally attempt to fix this. Are you able to re-run the analysis using the the code on `dev`? We are planning to release this soon and if you are still having issues then we can try and fix it.

```
nextflow pull nf-core/nanoseq
<YOUR_COMMAND> -r dev
```

**Comment by mlorthiois** [comment]
Hi, 
Thanks for the help, I'll run this quickly and come back to tell you if the problem is solved.

**Comment by mlorthiois** [comment]
Hi,

I re-run Nanoseq on the dev branch, with this command:
```
nextflow run nf-core/nanoseq \
    -profile singularity \
    --input input.csv \
    --protocol cDNA \
    --input_path /path/to/fast5_pass \
    --flowcell FLO-MIN106 \
    --kit SQK-DCS109 \
    --skip_demultiplexing \
    --max_cpus 30 \
    --igenomes_ignore false \
    --guppy_gpu true \
    -r dev
```
But I was not able to finish the analysis, here is what I got:
```
executor >  local (6)
[cd/582b09] process > CheckSampleSheet (input.csv)   [100%] 1 of 1 ✔
[62/8412d2] process > Guppy (fast5_pass)             [100%] 1 of 1 ✔
[f7/8133cd] process > PycoQC (sequencing_summary.... [100%] 1 of 1, failed: 1 ✘
[f1/36eefa] process > NanoPlotSummary (sequencing... [100%] 1 of 1 ✔
[-        ] process > NanoPlotFastQ                  -
[-        ] process > FastQC                         -
[-        ] process > GetChromSizes                  -
[-        ] process > GTFToBED                       -
[-        ] process > MiniMap2Index                  -
[-        ] process > MiniMap2Align                  -
[-        ] process > SortBAM                        -
[-        ] process > BAMToBedGraph                  -
[-        ] process > BedGraphToBigWig               -
[-        ] process > BAMToBed12                     -
[-        ] process > Bed12ToBigBed                  -
[-        ] process > Bambu                          -
[-        ] process > DESeq2                         -
[-        ] process > DEXseq                         -
[fb/3d017c] process > output_documentation           [100%] 1 of 1 ✔
[da/81e929] process > get_software_versions          [100%] 1 of 1, failed: 1 ✘
[-        ] process > MultiQC                        -
-[nf-core/nanoseq] Pipeline completed with errors-
WARN: To render the execution DAG in the required format it is required to install Graphviz -- See http://www.graphviz.org for more info.
Error executing process > 'PycoQC (sequencing_summary.txt)'

Caused by:
  Process `PycoQC (sequencing_summary.txt)` terminated with an error exit status (127)

Command executed:

  pycoQC -f sequencing_summary.txt -o pycoQC_output.html

Command exit status:
  127

Command output:
  (empty)

Command error:
  .command.sh: line 2: pycoQC: command not found
```

**Comment by drpatelh** [comment]
Thanks @mlorthiois. Ok, thats odd. The only reason I can think of is that we have had to use a [separate container for `pycoQC`](https://github.com/nf-core/nanoseq/blob/69dcb4eb45eccf87d52d4ee8ca3dbec4b2f3e556/conf/base.config#L57-L59) because I wasn't able to add it to the main Conda environment for the pipeline due to dependency conflicts. 

That container I linked to above should get downloaded when you run the pipeline with the parameters you used though. Can you try and add `export NXF_SINGULARITY_CACHEDIR=./containers/` before you run the command and it should download all of the containers for the pipeline in that directory.

**Comment by mlorthiois** [comment]
Thanks. I tried, but the new dev version tries to download the container nanoseq-1.1.0, without success. So I'll wait until it is available on docker hub to retry.

**Comment by drpatelh** [comment]
Ok. Yes, sorry 🤦 This is turning into a bit of hack. Can you run with `-r master` instead. That should work.

**Comment by mlorthiois** [comment]
I have the same error ...

```
Caused by:
  Failed to pull singularity image
  command: singularity pull  --name nfcore-nanoseq-1.1.0.img docker://nfcore/nanoseq:1.1.0 > /dev/null
  status : 255
  message:
    FATAL:   While making image from oci registry: error fetching image to cache: failed to get checksum for docker://nfcore/nanoseq:1.1.0: Error reading manifest 1.1.0 in docker.io/nfcore/nanoseq: manifest unknown: manifest unknown

```

**Comment by mlorthiois** [comment]
Ok I've been able to launch the new version 1.1.0. I still have the same problem ...
I attached my stdout, my log file and here are my commands :

```
export NXF_SINGULARITY_CACHEDIR=./containers/

nextflow pull nf-core/nanoseq

nextflow run nf-core/nanoseq \
    -profile singularity \
    --input input.csv \
    --protocol cDNA \
    --input_path data \
    --flowcell FLO-MIN106 \
    --kit SQK-DCS109 \
    --skip_demultiplexing \
    --max_cpus 16 \
    --guppy_gpu true \
    -r 1.1.0
```

[slurm-3327039.txt](https://github.com/nf-core/nanoseq/files/5501548/slurm-3327039.txt)
[nextflow.log](https://github.com/nf-core/nanoseq/files/5501551/nextflow.log)

**Comment by drpatelh** [comment]
Can you delete your `~/.singularity` directory and try again?

**Comment by drpatelh** [comment]
See [here](https://github.com/nf-core/rnaseq/issues/482#issuecomment-722617824)

**Comment by mlorthiois** [comment]
Done, but same problem ...

**Comment by drpatelh** [comment]
Ok. So now you don't have an issues with the download of the container? The pipeline finishes successfully but it still skips all of the alignment steps 🤦 Yeah, will need to keep this issue open then until I have time to fix this properly before the next release. Sorry, I thought the igenomes fix would work but it clearly hasn't...Thanks for bearing with me @mlorthiois 😎

**Comment by mlorthiois** [comment]
Oh yes, sorry, I didn't specify. Yes I downloaded the container without any problem. I just still have the initial problem of the skipped steps.
Thanks for the help, I'll keep looking on my side, if I find a solution I'll come back here 👍

**Comment by drpatelh** [comment]
This should be fixed when this commit is merged into `dev` @mlorthiois https://github.com/nf-core/nanoseq/pull/102/commits/34c7f08e72d7ba0490a771dd31f4c68d421e64ac . Will close this now but if the issue persists then please feel free to re-open. Apologies for the delay in getting around to fixing this and thanks for your help in debugging. Turned out to be a simple channel issue with the way the info is provided for data that requires basecalling but not demultiplexing.

Merry Xmas and Happy New Year!
