### ISSUE TITLE
Add optionnal DNA cleaning option

### ISSUE THREAD

**Issue by RxLoutre** [nf-core/nanoseq#97]
Hello everyone !

Thank you for the work on nanoseq !

Often in Nanopore sequencing, there is a QC DNA that must be added during the library prepatation which are known portion of the lambda phage, called DNA CS. There is an existing tool that we are using to remove the read corresponding to this DNA control before handing them to research team called nanolyse : https://github.com/wdecoster/nanolyse .

The tool take fastq as input from stdin and give the cleaned sequences in stdout. It is possible to also add as an input the sequencing summary and as an output the cleaned sequencing summary, so the short read from the DNA_cs do not disturb the QC tools on the median and N50 metrics of usable reads (QC tools often take the sequencing_summary as an input).

I am a very beginner in nextflow, and before I discovered nanoseq, I was trying to do that myself. If someone feels more comfortable doing it and adding it to nanoseq, that would be great !

I will be continuing to work on it on my side and I can give a hand if needed but as I said, I am very noobish in nextflow...

Have a great day !

Roxane

**Comment by drpatelh** [comment]
Hi @RxLoutre ! Hope you and loved ones are well! Thank you for all of the info. From what you have mentioned it should be quite straightforward to slip this process in after the basecalling/demultiplexing steps i.e. [before PycoQChere](https://github.com/nf-core/nanoseq/blob/ad5b2bb7a37a6edb9f61603636bd26e43259f58b/main.nf#L521) and then we can feed in the "cleaned" samplesheet as well as FastQ files into the downstream processes. The tool is also on [Bioconda](https://anaconda.org/bioconda/nanolyse) which is great.

I am not going to have the time to do this anytime soon I'm afraid but would welcome any contributions. In the meantime, as you have probably realised the pipeline can take fastq input so you could clean outside of the pipeline and feed that back in and it should work.

Also, maybe come and have a chat with us on #nanoseq channel on [nf-core Slack](https://nf-co.re/join) and we can see if anyone else there is willing to help out here.

**Comment by drpatelh** [comment]
Will be fixed in https://github.com/nf-core/nanoseq/pull/99 and https://github.com/nf-core/nanoseq/pull/102
